feat: release v2.6.1
api7/lua-resty-radixtree pull request #89
Opened 2021-01-20 11:29 UTC by spacewander

2021-01-20 12:10 UTC, membphis requested changes

2021-01-20 12:10 UTC, membphis commented on rockspec/lua-resty-radixtree-2.6.1-0.rockspec
> +package = "lua-resty-radixtree-master"
should be `lua-resty-radixtree`

2021-01-20 12:11 UTC, membphis commented
I modify it first and released a new version:

![image](https://user-images.githubusercontent.com/6814606/105173205-a72fa080-5b5b-11eb-8123-8a8a544ab0d4.png)

2021-01-20 13:06 UTC, spacewander commented on rockspec/lua-resty-radixtree-2.6.1-0.rockspec
> +package = "lua-resty-radixtree-master"
fixed

2021-01-20 13:08 UTC, moonming approved these changes

2021-01-21 01:33 UTC, membphis approved these changes

2021-01-21 01:33 UTC, merged